### ISSUE TITLE
JAVASCRIPT-Objetos- Introducción, métodos

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/chacoDevsTeam-3Semestre#112]
Se requiere desarrollar un objeto, establecer atributos, mostrar con Console.log el valor de los atributos y luego crear un método dentro del objeto que concatene el atributo nombre y apellido. Mostrar su valor con console.log (video 1, 2 y 3)

**Comment by Renzo-Espinola** [comment]
Se reviso el codigo y se integro, se espera por los demas tickets para la prueba integradora.

**Comment by naty33** [comment]
Las pruebas fueron exitosas se procede a cerrar la incidencia.
