### ISSUE TITLE
PYTHON-Clase de conexion-Postgresql con Python

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/chacoDevsTeam-3Semestre#113]
Se requiere desarrollar una clase que establezca una conexión Postgresql con Python y además se solicita utilizar el método fetchall de una sentencia de consulta a la base de datos, una vez terminado cerrar la conexión(Video 6, 7)

**Comment by Renzo-Espinola** [comment]
Se comienza el desarrollo.

**Comment by naty33** [comment]
Las pruebas fueron exitosas se procede a cerrar la incidencia.
