### ISSUE TITLE
JAVASCRIPT-Diferentes formas de crear un objeto

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/chacoDevsTeam-3Semestre#114]
Se requiere desarrollar un método alternativo para crear objetos diferentes al utilizado en el ticket #112(Video 4)

**Comment by patiky** [comment]
finalizado el desarrollo

**Comment by Renzo-Espinola** [comment]
Se reviso el codigo y se integro, se espera por los demas tickets para la prueba integradora.
