### ISSUE TITLE
JAVASCRIPT-Acceder a las propiedades del objeto

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/chacoDevsTeam-3Semestre#115]
Se requiere utilizar la estructura For In para acceder a las propiedades que posee el objeto Persona(video 5)

**Comment by Federico65744** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
Se reviso el codigo y se integro, se espera por los demas tickets para la prueba integradora.

**Comment by naty33** [comment]
Las pruebas fueron exitosas se procede a cerrar la incidencia.
