### ISSUE TITLE
JAVASCRIPT-Agregar y eliminar propiedades de Objeto

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/chacoDevsTeam-3Semestre#116]
Se requiere desarrollar sobre el objeto Persona un nuevo atributo luego eliminarlo y mostrar por consola(video 6)

**Comment by AlejoHGZ** [comment]
Se inicia el desarrollo del programa

**Comment by Renzo-Espinola** [comment]
Se reviso el codigo y se integro, se espera por los demas tickets para la prueba integradora.

**Comment by naty33** [comment]
Las pruebas fueron exitosas se procede a cerrar la incidencia.
