### ISSUE TITLE
JAVASCRIPT-Distintas formas de imprimir un objeto

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/chacoDevsTeam-3Semestre#118]
Se requiere desarrollar diferentes formas de imprimir un objeto y sus atributos(concatenación, For In, array, y Json)-(video 8)

**Comment by TatianaGimenezRios** [comment]
Se inicia el desarrollo.

**Comment by naty33** [comment]
Las pruebas fueron exitosas se procede a cerrar la incidencia.
