### ISSUE TITLE
JAVA-Manejo de Foreach

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/chacoDevsTeam-3Semestre#123]
Se requiere crear una clase test donde se pueda poner en practica la estructura Foreach tanto para un arreglo conformado por elementos primitivos y otro arreglo conformado por un objeto persona(Video 1 y 2)

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by naty33** [comment]
Las pruebas fueron exitosas se procede a cerrar la incidencia.
