### ISSUE TITLE
JAVA-Autoboxing-Unboxing

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/chacoDevsTeam-3Semestre#124]
Se requiere crear una variable de tipo primitivo, Una segunda variable la cual sea de la clase Integer(Object). Aplicar el autoboxing a la segunda variabley crear una nueva variable de tipo primitivo y aplicar unboxing(Video 3 y 4)

**Comment by DiosJuanVero2015** [comment]
Se inicia el desarrollo del programa

**Comment by Renzo-Espinola** [comment]
Se reviso el codigo y se integro, se espera por los demas tickets para la prueba integradora.

**Comment by naty33** [comment]
Las pruebas fueron exitosas se procede a cerrar la incidencia.
