### ISSUE TITLE
JAVA-Modificadores de acceso público

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/chacoDevsTeam-3Semestre#125]
Se requiere crear una clase, método y atributo de tipo público(Video 5 y 6)

**Comment by patiky** [comment]
finalizado el desarrollo

**Comment by Renzo-Espinola** [comment]
Se reviso el codigo y se integro, se espera por los demas tickets para la prueba integradora.

**Comment by naty33** [comment]
Las pruebas fueron exitosas se procede a cerrar la incidencia.
