### ISSUE TITLE
JAVA-Modificaciones de acceso de tipo Protected

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/chacoDevsTeam-3Semestre#126]
Se requiere crear una clase que sea hija de la clase uno.(Se debe esperar a la integración del ticket 125)(Video 7)

**Comment by Renzo-Espinola** [comment]
Se reviso el codigo y se integro, se espera por los demas tickets para la prueba integradora.

**Comment by naty33** [comment]
Las pruebas fueron exitosas se procede a cerrar la incidencia.
