### ISSUE TITLE
JAVA-Modificador de acceso de tipo private

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/chacoDevsTeam-3Semestre#128]
Se requiere crear una clase que contenga método, atributo, constructor del tipo private(Video 10)

**Comment by JuanValladaresv2** [comment]
Se comienza el desarrollo

**Comment by Renzo-Espinola** [comment]
Se reviso el codigo y se integro, se espera por los demas tickets para la prueba integradora.

**Comment by naty33** [comment]
Las pruebas fueron exitosas se procede a cerrar la incidencia.
