### ISSUE TITLE
JAVA-Creación de la Clase Padre

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#139]
Se requiere crear una clase padre con sus atributos,su consctructor y metodo(Video 1)

**Comment by JuanValladaresv2** [comment]
Se comienza el desarrollo

**Comment by Renzo-Espinola** [comment]
se reviso el codigo, y se puede integrar, se debe esperar a las pruebas finales para cerrar el ticket.

**Comment by NicoBalbuena** [comment]
Prueba final realizada con éxito,se cierra ticket.
