### ISSUE TITLE
JAVA-Creación de la clase hija

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#140]
Se requiere crear la clase hija y tambien la clase test.Luego sobreescribir la clase padre y probar(Video 2 y 3)

**Comment by Renzo-Espinola** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
se  integro pero se debe esperar a las pruebas finales para cerrar el ticket.

**Comment by NicoBalbuena** [comment]
Prueba final realizada con éxito,se cierra ticket.
