### ISSUE TITLE
JAVA-Definir variables para clase Test

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#141]
Se requiere definir variables en la clase test provenientes de la clase padre e hija.Por ultimo se solicita crear el metodo imprimir.(Video 4)

**Comment by Renzo-Espinola** [comment]
se reviso el codigo, y se puede integrar, se debe esperar a las pruebas finales para cerrar el ticket.

**Comment by NicoBalbuena** [comment]
Prueba final realizada con éxito,se cierra ticket.
