### ISSUE TITLE
JAVA-Modificar clase test

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#142]
Se requiere modificar variables y metodo imprimir en la clase test para comprobar funcionamiento del polimorfismo(Video 6)

**Comment by Renzo-Espinola** [comment]
se reviso el codigo, y se puede integrar, se debe esperar a las pruebas finales para cerrar el ticket.

**Comment by NicoBalbuena** [comment]
Prueba final realizada con éxito,se cierra ticket.
