### ISSUE TITLE
JAVA-Creación de nuevo proyecto

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#143]
Se requiere copiar el proyecto y colocar el nombre de  instanceof.En la clase test cambiar TestInstanceof.Volver a modificar variables y metodo.(video 7 )

**Comment by AlejoHGZ** [comment]
Se inicia el desarrollo del proyecto

**Comment by Renzo-Espinola** [comment]
se reviso el codigo, y se puede integrar, se debe esperar a las pruebas finales para cerrar el ticket.

**Comment by NicoBalbuena** [comment]
Prueba final realizada con éxito,se cierra ticket.
