### ISSUE TITLE
JAVA-Clase empleado

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#144]
Agregar en la clase Empleado el get y set.Luego modificar el metodo determinarTipo con ambas formas de conversiones (video 9 y 10)

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
se reviso el codigo, y se puede integrar, se debe esperar a las pruebas finales para cerrar el ticket.

**Comment by NicoBalbuena** [comment]
Prueba final realizada con éxito,se cierra ticket.
