### ISSUE TITLE
PYTHON-CONSULTA DE UN REGISTRO

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#165]
Modificar la clase prueba_bd.py sentencia select, execute de la sentencia, que se ingrese por teclado el id (VIDEO 1 y 2)

**Comment by Renzo-Espinola** [comment]
Se comienza con el desarrollo.

**Comment by Renzo-Espinola** [comment]
se integra, pero se debe esperar a las pruebas finales antes de finalizar.

**Comment by Ventc** [comment]
Prueba final realizada con exito.
