### ISSUE TITLE
PYTHON-CONSULTA DE VARIOS REGISTROS

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#166]
Crear una clase nueva de python v_registros.py la cual realize una consulta select en un rango de id ingresados por teclado (VIDEO 3 y 4)

**Comment by Renzo-Espinola** [comment]
Integrado, pero se debe esperar a las pruebas finales para cerrar incidencia

**Comment by Ventc** [comment]
Prueba final realizada con exito.
