### ISSUE TITLE
PYTHON-INSERT DE UN REGISTRO

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#167]
Crear una clase nueva de python i_registros.py donde se cree una sentencia Insert, esta debe realizar un insert en la tabla persona con los campos nombre, apellido, mail (VIDEO 5)

**Comment by Renzo-Espinola** [comment]
se integra, pero se debe esperar a las pruebas finales antes de finalizar.

**Comment by Ventc** [comment]
Prueba final realizada con exito.
