### ISSUE TITLE
PYTHON-UPDATE DE 1 REGISTRO

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#168]
Crear una clase nueva actualizar_registros.py, esta debe realizar una sentencia UPDATE de un registro existente en la tabla persona (VIDEO 7)

**Comment by JuanValladaresv2** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
se integra, pero se debe esperar a las pruebas finales antes de finalizar.

**Comment by Ventc** [comment]
Prueba final realizada con exito.
