### ISSUE TITLE
PYTHON-UPDATE DE VARIOS REGISTROS

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#169]
Crear una clase nueva actualizar_varios_registros.py, esta debe realizar una sentencia UPDATE de varios registros existentes en la tabla persona (VIDEO 8)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
se integra, pero se debe esperar a las pruebas finales antes de finalizar.

**Comment by Ventc** [comment]
Prueba final realizada con exito.
