### ISSUE TITLE
PYTHON-DELETE DE 1 REGISTRO

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#170]
Crear una clase nueva delete_registros.py, esta debe realizar una sentencia DELETE de 1 registro existente en la tabla persona, este ID debe ser ingresado por teclado (VIDEO 9)

**Comment by Federico65744** [comment]
Se comienza con el desarrollo

**Comment by Renzo-Espinola** [comment]
se integra, pero se debe esperar a las pruebas finales antes de finalizar.

**Comment by Ventc** [comment]
Prueba final realizada con exito.
