### ISSUE TITLE
JS-METODOS GET & SET

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#171]
Se requiere llamar una funcion utilizando el metodo get & set (Video 1 y 2)

**Comment by AlejoHGZ** [comment]
Se inicia el desarrollo

**Comment by Renzo-Espinola** [comment]
se integra, pero se debe esperar a las pruebas finales antes de finalizar.

**Comment by Ventc** [comment]
Prueba final realizada con exito.
