### ISSUE TITLE
JS-AGREGAR METODOS AL CONSTRUCTOR DEL OBJETO

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#173]
Se requiere agregar métodos al constructor (Video 4)

**Comment by DiosJuanVero2015** [comment]
Se inicia el Desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado, pero se debe esperar a las pruebas finales para cerrar incidencia.

**Comment by Ventc** [comment]
Prueba final realizada con exito.
