### ISSUE TITLE
JS-USO DE PROTOTYPE

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#175]
Se requiere agregar la propiedad prototype y mostrar los ejemplos (Video 6)

**Comment by JuanValladaresv2** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
se integra, pero se debe esperar a las pruebas finales antes de finalizar.

**Comment by Ventc** [comment]
Prueba final realizada con exito.
