### ISSUE TITLE
JS-USO DE CALL

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#176]
Se requiere crear los objetos persona4 y persona5, utilizando el metodo call en este ultimo objeto (Video 7)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
se integra, pero se debe esperar a las pruebas finales antes de finalizar.

**Comment by Ventc** [comment]
Prueba final realizada con exito.
