### ISSUE TITLE
JS-USO DE APPLY

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#177]
Se requiere utilizar el metodo apply y mostrar los ejemplos (Video 8)

**Comment by Renzo-Espinola** [comment]
Se comienza con el desarrollo.

**Comment by Renzo-Espinola** [comment]
se integra, pero se debe esperar a las pruebas finales antes de finalizar.

**Comment by Ventc** [comment]
Prueba final realizada con exito.
