### ISSUE TITLE
JAVA-CONVERSION DE OBJETOS

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#190]
Se requiere una conversion de objetos casting (Video 1)

**Comment by Renzo-Espinola** [comment]
Se comienza con el desarrollo.

**Comment by Renzo-Espinola** [comment]
se integra, pero se debe esperar a las pruebas finales antes de finalizar.

**Comment by Ventc** [comment]
Prueba final realizada con exito.
