### ISSUE TITLE
JAVA-HASHCODE Y EQUALS

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#193]
Se requiere comparar los atributos de la clase utilizando la variable "this" u "other" (Video 5)

**Comment by DiosJuanVero2015** [comment]
Se inicia el desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado, pero se debe esperar a las pruebas finales para cerrar incidencia

**Comment by Ventc** [comment]
Prueba final realizada con exito.
