### ISSUE TITLE
JAVA-CLASES ABSTRACTAS

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/chacoDevsTeam-3Semestre#194]
Se requiere la creación de una clase padre "FiguraGeometrica" y clases hijas "Rectangulo" (Video 6 y 7)

**Comment by Renzo-Espinola** [comment]
se integra, pero se debe esperar a las pruebas finales antes de finalizar.

**Comment by Ventc** [comment]
Prueba final realizada con exito.
