### ISSUE TITLE
PYTHON - MANEJO DE TRANSACCIONES

### ISSUE THREAD

**Issue by AlejoHGZ** [CodeSystem2022/chacoDevsTeam-3Semestre#213]
Se requiere crear una clase llamada transacciones.py en el que se solicita desarrollar la conexion y transaccion sin with (video 3,4)

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado pero se debe esperar a las pruebas finales

**Comment by AlejoHGZ** [comment]
Se realizaron las pruebas y Fueron satisfactorias.
