### ISSUE TITLE
PYTHON - MANEJO DE TRANSACCIONES CON VARIAS SENTENCIAS

### ISSUE THREAD

**Issue by AlejoHGZ** [CodeSystem2022/chacoDevsTeam-3Semestre#214]
Se require crear una clase llamada transacciones_dos.py en el que se solicita desarrollar la conexion sin with ejecutar 2 sentencias de transacciones (video 5 y 6)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado pero se debe esperar a las pruebas finales

**Comment by AlejoHGZ** [comment]
Se realizaron las pruebas y Fueron satisfactorias.
