### ISSUE TITLE
JAVASCRIPT - SINTAXIS DE CLASES

### ISSUE THREAD

**Issue by AlejoHGZ** [CodeSystem2022/chacoDevsTeam-3Semestre#216]
Crear clase persona con atributos nombre y apellidos (videos 1 y 2) - Bloqueante para los demas tickets

**Comment by Renzo-Espinola** [comment]
integrado pero se debe esperar a las pruebas finales

**Comment by AlejoHGZ** [comment]
Se realizaron las pruebas y Fueron satisfactorias.
