### ISSUE TITLE
JAVASCRIPT - METODO GET Y SET

### ISSUE THREAD

**Issue by AlejoHGZ** [CodeSystem2022/chacoDevsTeam-3Semestre#217]
Se requiere agregar metodo get y seter del atributo nombre, usar console.log para mostrar su estado (video 3 y 4)

**Comment by DiosJuanVero2015** [comment]
Se inicia desarrollo

**Comment by AlejoHGZ** [comment]
Se realizaron las pruebas y Fueron satisfactorias.
