### ISSUE TITLE
JAVASCRIPT - TAREA HOISTING

### ISSUE THREAD

**Issue by AlejoHGZ** [CodeSystem2022/chacoDevsTeam-3Semestre#218]
Se requiere crear geter and seter  del atributo apellido, usar console.log para visualizar su estado y aplicar el concepto a clases (Tarea - VIDEO 5 y 6)

**Comment by JuanValladaresv2** [comment]
Se inicia desarrollo

**Comment by Renzo-Espinola** [comment]
integrado pero se debe esperar a las pruebas finales

**Comment by AlejoHGZ** [comment]
Se realizaron las pruebas y Fueron satisfactorias.
