### ISSUE TITLE
JAVASCRIPT -  HERENCIA

### ISSUE THREAD

**Issue by AlejoHGZ** [CodeSystem2022/chacoDevsTeam-3Semestre#219]
Crear clase hija "empleado" agregar un atributo "departamento" con sus respectivos geter and seter, crear un nuevo objeto "empleado" y mostrar su estado con concole.log (video 7 y 8)

**Comment by Renzo-Espinola** [comment]
Se comienza el desarrollo

**Comment by Renzo-Espinola** [comment]
integrado pero se debe esperar a las pruebas finales

**Comment by AlejoHGZ** [comment]
Se realizaron las pruebas y Fueron satisfactorias.
