### ISSUE TITLE
PYTHON 1 ETAPA-Paquete domain-Clase autor.py

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#225]
Se requiere el desarrollo de la clase autor, la cual debe heredar de la clase persona encapsular sus atributos con sus respectivos getter and setter.
Atributos propios: 
libros publicados,libros escritos 
Metodos:
init y str

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
Se integro y se estan realizando pruebas.

**Comment by Renzo-Espinola** [comment]
Prueba final realizada con exito.
