### ISSUE TITLE
PYTHON 1 ETAPA-Paquete domain-Clase socio.py

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#227]
Se requiere el desarrollo de la clase socio, la cual debe heredar de la clase persona encapsular sus atributos con sus respectivos getter and setter.
Atributos propios:
libros_prestados, fecha_alta, id_socio
Metodos:
init y str

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
Se integro y se estan realizando pruebas.

**Comment by Renzo-Espinola** [comment]
Prueba final realizada con exito.
