### ISSUE TITLE
PYTHON 1 ETAPA-Paquete enum-Enum estado_libro.py

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#230]
Se requiere crear una clase de tipo ENUM llamada estado de libro, esta enumerara 2 tipos de estado DEVUELTO y NO DEVUELTO la misma servira para determinar el estado de un libro.

**Comment by DiosJuanVero2015** [comment]
se inicia desarrollo

**Comment by Renzo-Espinola** [comment]
Se integro y se estan realizando pruebas.

**Comment by Renzo-Espinola** [comment]
Prueba final realizada con exito.
