### ISSUE TITLE
PYTHON - Manejo de logging - parte 1

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/chacoDevsTeam-3Semestre#239]
Se requiere crear la carpeta Leccion07->capa_datos_persona dentro del directorio crear la clase logger_base.py se debe desarrollar la configuracion de logs y mostrar los mensajes de los diferentes niveles (Video 2 y 3)

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado, se espera por pruebas integradoras para cerrar esta incidendencia.

**Comment by Federico65744** [comment]
Prueba final realizada con éxito.

**Comment by Federico65744** [comment]
Prueba final realizada con éxito.
