### ISSUE TITLE
PYTHON - Manejo de logging: parte 2

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/chacoDevsTeam-3Semestre#240]
se requiere agregar las lineas de configuracion  donde se visualize la hora-nivel-clase y mensaje (video 4)

**Comment by Renzo-Espinola** [comment]
Integrado, se espera por pruebas integradoras para cerrar esta incidendencia.

**Comment by Renzo-Espinola** [comment]
Integrado, se espera por pruebas integradoras para cerrar esta incidendencia.

**Comment by Federico65744** [comment]
Prueba final realizada con exito.

**Comment by Federico65744** [comment]
Prueba final realizada con éxito.
