### ISSUE TITLE
JAVASCRIPT - Herencia de métodos

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/chacoDevsTeam-3Semestre#241]
HERENCIA - se requiere crear un metodo en la clase padre y utilizarlo en la clase hija (video 1)

**Comment by Renzo-Espinola** [comment]
Integrado, se espera por pruebas integradoras para cerrar esta incidendencia.

**Comment by Federico65744** [comment]
Prueba final realizada con éxito, se cierra ticket.
