### ISSUE TITLE
JAVASCRIPT - Sobreescritura de metodos

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/chacoDevsTeam-3Semestre#242]
se requiere crear un metodo en la clase hija que sobrescriba el metodo nombreCompleto definido en la clase padre (video 2)
Se debe crear el index.html

**Comment by Renzo-Espinola** [comment]
Integrado, se espera por pruebas integradoras para cerrar esta incidendencia.

**Comment by Federico65744** [comment]
Prueba final realizada con éxito, se cierra ticket.
