### ISSUE TITLE
JAVASCRIPT - Object-toString()-polimorfismo Parte 1

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/chacoDevsTeam-3Semestre#243]
OBJECT-toSTRING() parte 1-Se require crear un metodo toString() en la clase padre y llamarlo desde un objeto de la clase hija(video3)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado, se espera por pruebas integradoras para cerrar esta incidendencia.

**Comment by Federico65744** [comment]
Prueba final realizada con éxito, se cierra ticket.
