### ISSUE TITLE
JAVASCRIPT - Object-toString()-polimorfismo Parte 2

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/chacoDevsTeam-3Semestre#244]
OBJECT-toString() parte 2 - agregar console log que apunte a la clase padre
Realizar documentacion sobre el codigo

**Comment by Renzo-Espinola** [comment]
Se comienza desarrollo.

**Comment by Federico65744** [comment]
Integrado, se espera por pruebas integradoras para cerrar esta incidendencia.

**Comment by Federico65744** [comment]
Prueba final realizada con éxito, se cierra ticket.
