### ISSUE TITLE
PYTHON  2 ETAPA-Capa UI-ui.py

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#259]
Se require crear los menus:
1) ABM: Socio, Autor, Libro

2) Menu de seleccion de ABM

3) Menu Principal

4) Menu de Retiro y Solicitud

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
Prueba final realizada con exito.
