### ISSUE TITLE
PYTHON-Creación de la Clase Persona

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#268]
Se requiere crear la clase persona con los siguientes atributos id_persona,nombre,apellido, email,
debe tener los siguientes metodos: init y str
definir getter y setters para encapsular cada atributo.
se debe crear también un método de prueba de la clase persona (Video 1 y 2)

**Comment by Renzo-Espinola** [comment]
se integra lo desarrollado, pero se debe esperar a las pruebas finales para cerrar este issue
