### ISSUE TITLE
PYTHON-Creación de la Clase Conexion

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#269]
se requiere crear la clase conexion se debe crear atributos de clase _DATABASE = 'test_bd'
    _USERNAME = 'postgres'
    _PASSWORD = 'admin'
    _DB_PORT = '5432'
    _HOST = '127.0.0.1'
    _CONEXION = None
    _CURSOR = None
y los metodos de clase:
obtenerConexion (VIDEOS 3 y 4)

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
se integra lo desarrollado, pero se debe esperar a las pruebas finales para cerrar este issue
