### ISSUE TITLE
PYTHON-Creación de la Clase Conexion (Parte2)

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#270]
se requiere crear en la misma clase Conexion el metodo obtenerCursor() 
ademas de crear un metodo de prueba de ambos metodos.
Realizar la correccion de los errores en los metodos creados (VIDEO 5 y 6)

**Comment by AlejoHGZ** [comment]
Se inicia el desarrollo
