### ISSUE TITLE
PYTHON-creación de la Clase PersonaDAO

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#271]
Se requiere crear la clase persona_dao y definir los atributos de clase 
 _SELECCIONAR 
    _INSERTAR 
    _ACTUALIZAR 
    _ELIMINAR
(VIDEO 7)

**Comment by Renzo-Espinola** [comment]
Integrado, se debe esperar por las pruebas finales
