### ISSUE TITLE
JAVASCRIPT- Palabra static con métodos

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#272]
se requiere crear 2 metodos statics uno con parámetro y el otro sin parámetro dentro 
de la clase Persona, se debe mostrar por consola tanto con la clase Padre y con la clase hija
(video 1 y 2)

**Comment by TatianaGimenezRios** [comment]
Se inicia el desarrollo.

**Comment by Renzo-Espinola** [comment]
se integra lo desarrollado, pero se debe esperar a las pruebas finales para cerrar este issue
