### ISSUE TITLE
JAVASCRIPT-Atributos estáticos

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#273]
se requiere crear un atributo static que sea un contador de objetos del tipo persona
el mismo se debe mostrar por consola tanto clase hija y padre(VIDEO 3)

**Comment by Federico65744** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
se integra lo desarrollado, pero se debe esperar a las pruebas finales para cerrar este issue
