### ISSUE TITLE
JAVASCRIPT-Atributos estáticos vs No estáticos

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#274]
Se require crear un atributo no estatico  dentro de la clase Persona y utilizar
console log para mostrar el atributo nuevo, tanto para la clase hija y la clase padre(VIDEO 4)

**Comment by Renzo-Espinola** [comment]
se integra lo desarrollado, pero se debe esperar a las pruebas finales para cerrar este issue
