### ISSUE TITLE
JAVASCRIPT-Uso de la palabra static: Parte 1 y 2

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#275]
se requiere modificar el atributo contadorObjetoPersona por contadorPersona
modificar el metodo nombreCompleto agregar el id de persona
se requiere asignar el valor del contadorPersona a un atributo idPersona
mostrar mediante console log los 3 objetos creados el valor de sus atributos con el metodo toString()
Ademas se requiere un objeto nuevo del tipo persona mostrar sus atributos con el toString
y mostrar el atributo static contadorPersona(Video 5 y 6)

**Comment by Renzo-Espinola** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
se integra lo desarrollado, pero se debe esperar a las pruebas finales para cerrar este issue
