### ISSUE TITLE
JAVASCRIPT-Creación de constantes estáticas

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#276]
e requiere crear un metodo static get MAX_OBJ() el cual se utilizara para establecer una
condicion de generacion de idPersona en el caso de que sea menor sumara 1 en caso contrario
se mostrara el siguiente mensaje: se ha superado el maximo de objetos permitidos
se deberan crear 2 objetos nuevos del tipo persona

**Comment by Renzo-Espinola** [comment]
Integrado, se debe esperar por las pruebas finales
