### ISSUE TITLE
JAVA - Manejo de JavaBeans

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#282]
Se requiere crear un nuevo proyecto con el nombre "JavaBeans", ademas se requiere crear una clase "persona" (Clase 8, Video 1)

**Comment by Renzo-Espinola** [comment]
Integrado, se debe esperar por las pruebas finales

**Comment by Renzo-Espinola** [comment]
Se realizo un hotfix sobre el proyecto
