### ISSUE TITLE
JAVA - Prueba de JavaBeans

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#283]
Se requiere crear una clase "TestJavaBeans" para realizar pruebas (clase 8, video 2)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
se integra lo desarrollado, pero se debe esperar a las pruebas finales para cerrar este issue
