### ISSUE TITLE
JAVA - Manejo de Excepciones Pt 1

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#284]
(clase 8, Video 3 Pt1): Se requiere crear un nuevo proyecto con el nombre "ManejoExcepciones1", dentro, debemos crear una clase con el nombre "TextExcepciones"

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado, se debe esperar por las pruebas finales
