### ISSUE TITLE
JAVA - Manejo de Excepciones Pt 2, 3 y 4

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#285]
(clase 8, video 4Pt2): Se requiere trabajar con Try 
(clase 8, video 5 Pt3, explicacion de los diagramas NO HACE CODIGO)
(clase 8, video 6 Pt4): Solo se requiere comentar el código.

**Comment by JuanValladaresv2** [comment]
Se comienza desarrollo
