### ISSUE TITLE
JAVA - Creación de Excepciones Pt 1,2 y 3

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/chacoDevsTeam-3Semestre#286]
(clase 8, video 7 Pt1): Se requiere crear una nueva clase con el nombre "OperacionExcepcion" 
(clase 8, video 8 Pt2): Se requiere crear una nueva clase con el nombre "Aritmética"
(clase 8, video 9 Pt3): Se requiere hacer uso de la Division, que se encuentra dentro de la clase "TextExcepciones"

**Comment by AlejoHGZ** [comment]
se inicia el desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado, se debe esperar por las pruebas finales
