### ISSUE TITLE
PYTHON-Metodo de clase Seleccionar

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#309]
Se requiere desarrollar en la clase persona_dao.py el metodo seleccionar el cual debe realizar una consulta a la tabla test_bd y obtener los registros de las personas cargadas se debe realizar la prueba correspondiente (Video 1 y 2)

**Comment by patiky** [comment]
desarrollo comenzado

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras sobre el proyecto de python

**Comment by Renzo-Espinola** [comment]
Se realiza pruebas exitosa sobre el metodo seleccionar se adjunta evidencias:


![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/0bbd7cdf-9c08-4549-aaf7-a23ac30133e0)

**Comment by Renzo-Espinola** [comment]
Se procede a cerrar esta incidencia.
