### ISSUE TITLE
PYTHON-Metodo de clase Insertar

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#310]
Se requiere  desarrollar en la clase persona_dao.py el metodo insertar el cual debe realizar una transaccion a la tabla test_bd la cual debe insertar un registro del tipo persona se debe realizar la prueba correspondiente (video 3)

**Comment by NicoBalbuena** [comment]
Se inicia desarrollo del ticket

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras sobre el proyecto de python

**Comment by Renzo-Espinola** [comment]
Se realizan prueba exitosa sobre el metodo insertar, se adjuntan evidencias:


![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/5ff771e2-4a5e-4c3c-9c3a-462cf33da952)

se verifica sobre los registros de la base de datos:


![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/b4e4b922-d5d2-414e-a1a1-c87d7457ffdb)
