### ISSUE TITLE
PYTHON-Metodo de clase Actualizar

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#311]
Se requiere desarrollar en la clase persona_dao.py el metodo actualizar el cual debe realizar una transaccion a la tabla_bd este debe actualizar un registro ya guardado mediante un id_persona se debe realizar la prueba correspondiente (video 4)

**Comment by JuanValladaresv2** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras sobre el proyecto de python

**Comment by Renzo-Espinola** [comment]
Para la siguiente prueba se toma el siguiente caso repetido en la base test_bd:
tabla = persona
id_persona = 4


![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/24349406-d3b5-499f-afac-64bd7feadac7)

Se procede a modificar el siguiente registro con datos nuevos:
Id Persona: 4,
Nombre: Juan José,
Apellido: Pena,
Email: jjpena@mail.com

![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/7ff9b9e5-e4f4-439c-aae3-ce3f83224e76)

Se procede a verificar en la BD en la tabla persona:


![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/3bbf59dd-c13e-4407-aafb-c5000fefe918)

Se verifica que el registro fue modificado como se espera, se procede a cerrar esta incidencia.
