### ISSUE TITLE
PYTHON-Metodo de clase Eliminar

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#312]
Se requiere desarrollar en la clase persona_dao.py el metodo eliminar el cual debe realizar una transaccion a la tabla_bd este debe eliminar un regsitro ya guardado mediante un id_persona se debe realizar la prueba correspondiente ademas de realizar la correccion para el metodo SELECCIONAR (video 5 y 6)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras sobre el proyecto de python

**Comment by Renzo-Espinola** [comment]
Para la siguiente prueba se toma el siguiente caso repetido en la base test_bd:
tabla = persona
id_persona = 6


![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/67b6e60e-5c6e-40e3-a293-b82bf3228e90)

Se verifica que el metodo eliminar funciono como se espera:


![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/27d90efa-4ba0-4f21-b34a-f5edb1b612de)

Se valida sobre los registros de la BD test_bd:


![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/9c4af1e6-805b-4963-86b1-33af1aa853ab)

Se verifica que el id_persona=6 ya no existe.

Se puede dar por finalizada esta incidencia.
