### ISSUE TITLE
JAVASCRIPT-Creación de la Clase Persona

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#313]
Se requiere crear en un directorio nuevo TSLeccion07 Persona.js donde vamos a crear la clase Persona, esta debe contar con un metodo static contadorPersona, y los atributos  nombre, apellido, edad estos deben ser encapsulados y contar con sus respectivos getter and setter ademas crear  el metodo toString() (video 2)

**Comment by Federico65744** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras.

**Comment by Renzo-Espinola** [comment]
Se crea un objeto del tipo persona para validar el funcionamiento de la clase Persona.


![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/da5d21c6-3cc9-4749-bf93-733b2bed1678)

La prueba fue exitosa, se puede cerrar esta incidencia.
