### ISSUE TITLE
JAVASCRIPT-Creación de la Clase Cliente

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#314]
Se requiere crear un archivo nuevo llamado Cliente.js donde  vamos extender a la clase Persona, esta debe contar con un metodo static contadorCliente, y su atributo propio fechaRegistro este debe ser encapsulado y contar con sus respectivos getter and setter ademas crear el metodo toString() (Video 4)

**Comment by naty33** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras.

**Comment by Renzo-Espinola** [comment]
Se crea un objeto Cliente para probar la funcionalidad de la clase Cliente, se movio la clase Persona para poder extender de ella.


![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/e3076d5a-d20e-4a6b-a69b-976e0cff0928)

Se verifica que su funcionamiento es el correcto, se procede a cerrar esta incidencia.
