### ISSUE TITLE
JAVASCRIPT-Creación de la Clase Empleado

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#315]
Se requiere crear un archivo nuevo llamado Empleado.js donde  vamos extender a la clase Persona, esta debe contar con un metodo static contadorEmpleado, y su atributo propio sueldo este debe ser encapsulado y contar con sus respectivos getter and setter ademas crear el metodo toString() Video 3

**Comment by AlejoHGZ** [comment]
se inicia el desarrollo

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras.

**Comment by Renzo-Espinola** [comment]
Se crea un objeto del tipo Empleado, se agrega la clase Persona para poder extender de ella.


![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/e63a1c5f-67d6-416e-8492-8fa9cc4b38ec)

Se verifica que el resultado es el esperado, se procede a cerrar esta incidencia.
