### ISSUE TITLE
JAVASCRIPT-Creación de la Clase PruebaPersona

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#316]
Se requiere crear un archivo nuevo llamado PruebaPersona.js donde  vamos agregar todas las clases creadas en los otros archivos(Persona,Empleado,Cliente) esto se debe a que JavaScript maneja el trabajo en MODULOS ademas se requiere realizar la prueba de la clase Persona (Video 5 y 6)

**Comment by DiosJuanVero2015** [comment]
Se inicia Desarrollo

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras.

**Comment by Renzo-Espinola** [comment]
Este ticket se realizara la prueba conjunta con el ticket N° #317
