### ISSUE TITLE
JAVASCRIPT-Prueba Clase Empleado y Cliente

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#317]
Se requiere crear las pruebas para las clases Empleado y Cliente creando 2 objetos por clase y mostrando sus atributos mediante el metodo toString() (video 7 y 8)

**Comment by Renzo-Espinola** [comment]
se finalizo el desarrollo del ticket #316 , se puede iniciar el desarrollo de este incidencia.

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras.

**Comment by Renzo-Espinola** [comment]
Se verifica que el resultado es el esperado.


![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/70241433/a1371ce5-886b-4ef0-bc8f-6dcdb74c207b)

Las pruebas fueron exitosas, se procede a cerrar esta incidencia.
