### ISSUE TITLE
JAVA-Definiendo las variables y Ponemos la entrada de información

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#322]
Se requiere crear en la carpeta Leccion09 el proyecto CalculadoraUTN, se deben definir las variables primero con hardcode y luego ingreso por teclado del usuario y realizar una operacion de suma, mostrar su resultado por consola (VIDEO 2 y 3)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras sobre el proyecto de python

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.
