### ISSUE TITLE
JAVA-Agregamos el switch en el MENU

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#323]
se requiere agregar una sentencia de control switch dentro de cada opcion establecer  la operacion, ademas de agregar una evaluacion por la opcion de salida y una evaluacion por ingreso erroneo. (PRIORITARIO HASTA TERMINAR TICKET 324) (VIDEO 5)

**Comment by Renzo-Espinola** [comment]
Se integro el ticket #324, se puede iniciar este desarrollo

**Comment by AlejoHGZ** [comment]
Se inicia desarrollo

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras sobre el proyecto de java.

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.
