### ISSUE TITLE
JAVA-Creamos y mostramos el MENU

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#324]
Se requiere crear el menu con las operaciones basicas suma,resta,multiplicacion,division colocar un evaluacion sobre el ingreso del usuario sobre la accion que quiere realizar(PRIORITARIO HASTA TERMINAR TICKET 322) (VIDEO 4)

**Comment by NicoBalbuena** [comment]
Se inicia desarrollo del ticket asignado

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras sobre el proyecto de java.

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.
