### ISSUE TITLE
JAVA-Agregamos try catch para las excepciones

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#326]
Se requiere agregar un manejador de excepciones TRY CATCH, este debe abarcar desde que inicia el ingreso del usuario para seleccionar una operacion. (BLOQUEADO HASTA TERMINAR TICKET 325) (VIDEO 7)

**Comment by NicoBalbuena** [comment]
Se inicia el desarrollo del código

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras sobre el proyecto de java.

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.
