### ISSUE TITLE
JAVA-Factorizamos el código a través del método mostrarMenu

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#327]
Se requiere crear una funcion donde migremos el menu principal y utilizemos esta funcion.   (BLOQUEADO HASTA TERMINAR TICKET 326) (video 8)

**Comment by Renzo-Espinola** [comment]
Integrado el ticket #326 se puede comenzar con este desarrollo.

**Comment by JuanValladaresv2** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras sobre el proyecto de java.

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.
