### ISSUE TITLE
JAVA-Función ejecutarOperacion y pruebas

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#328]
Se requiere crear una funcion donde migremos el ingreso del usuario  y las operaciones se requiere realizar las correcciones pertinentes en el tipo de variables INT a DOUBLE  (BLOQUEADO HASTA TERMINAR TICKET 327) (VIDEO 9-10)

**Comment by Renzo-Espinola** [comment]
se integro el ticket #327, se puede comenzar con este desarrollo.

**Comment by Federico65744** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
Se integra pero se espera para las pruebas integradoras antes de cerrar esta incidencia.

**Comment by Renzo-Espinola** [comment]
Se comienza a realizar las pruebas integradoras sobre el proyecto de java.

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.
