### ISSUE TITLE
JAVA-PROYECTO PCMUNDO-Clase Computadora

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/chacoDevsTeam-3Semestre#34]
Se requiere crear la clase Computadora la cual debe contar entre sus atributos nombre, monitor (de la clase Monitor), teclado(de la clase Teclado), raton (de la clase Raton), ademas de contar de un id de computadora

**Comment by Ventc** [comment]
Ya se integro a la main
