### ISSUE TITLE
PYTHON 2 ETAPA-Capa Service-service_autor.py

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#350]
Se requiere crear el service de autor el cual contrendra varias opciones a elegir por el usuario:
1).Nuevo autor: solicitara el ingreso de los datos del autor a guardar en BD.
2).Listado de autores: se realizara una consulta a la BD para traer todos los registros.
3).Baja autor: Mediante el ID ingresado por el usuario se dara de baja un autor.
4).Modificar datos de autor: Mediante un ID de autor se solicitara los datos para modificar un autor ya creado.

**Comment by TatianaGimenezRios** [comment]
Se inicia el desarrollo.

**Comment by Renzo-Espinola** [comment]
Prueba final realizada con exito.
