### ISSUE TITLE
PYTHON 2 ETAPA-Capa Service-service_libro.py

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#352]
Se requiere crear el service de libro el cual contrendra varias opciones a elegir por el usuario:
1).Nuevo libro: solicitara el ingreso de los datos de libro a guardar en BD, se solicitara el ingreso del ISBN se validara que no exista uno en BD, en caso de que exista se informara al usuario que debe realizar el proceso de actualizacion de cantidad, en caso contrario se proseguira con la solicitudde ingreso de datos, para el campo autor y socio se preguntara al usuario de que manera registrara asi se validara de que primero se hayan cargado en sus correspondientes tablas.
2).Listado de libros: se realizara una consulta a la BD para traer todos los registros.
3).Baja libro: Mediante el ID ingresado por el usuario se dara de baja un libro.
4).Modificar datos de libro: Mediante un ID de libro se solicitara los datos para modificar un libro ya creado.
5).Nuevo libro existente: esta opcion servira para agregar una cantidad a un libro que ya existe en BD asi solo se modificara la cantidad de que se posee en existencia, y no se requiere estar cargando todos los datos nuevamente.

**Comment by JuanValladaresv2** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
Prueba final realizada con exito.
