### ISSUE TITLE
PYTHON 2 ETAPA-Capa Service-service_socio.py

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#353]
Se requiere crear el service de socio el cual contrendra varias opciones a elegir por el usuario:
1).Nuevo socio: solicitara el ingreso de los datos del socio a guardar en BD.
2).Listado de socios: se realizara una consulta a la BD para traer todos los registros.
3).Baja socio: Mediante el ID ingresado por el usuario se dara de baja un socio.
4).Modificar datos de socios: Mediante un ID de autor se solicitara los datos para modificar un socio ya creado.

**Comment by naty33** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
Prueba final realizada con exito.
