### ISSUE TITLE
PYTHON 2 ETAPA-paquete test-test_gestion_biblioteca.py

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#355]
Se requiere crear la clase test_gestion_biblioteca.py la cual contara con varios metodos:
1).inicio(): este metodo se debe encargar de realizar la inicializacion de los procesos de BD (crear BD y tablas si no existen)

2).menu(): este metodo llamara al metodo inicio(), se deberan usar los metodos creados en la clase ui para generar el mensaje de menu principal.

3).ejecutar_opcion_abm: se encargar de los service de abm socio,autor,libro.

4).ejecutar_opcion_solicitud: se encargara del service de solicitud y devolucion.

5).ejecutar_opcion: debera controlar las opciones ingresadas por el usuario para los diferentes menus.

**Comment by Federico65744** [comment]
Se comenzó el desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado

**Comment by Renzo-Espinola** [comment]
Prueba final realizada con exito.
