### ISSUE TITLE
PYTHON- Obtener una conexión a partir del Pool:

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/chacoDevsTeam-3Semestre#357]
se requiere modificar la clase conexion, borrar el cuerpo de los metodos obtenerConexion y el metodo obtenerCursor, y crear el metodo de clase obtenerPool (video 2 y 3)

**Comment by TatianaGimenezRios** [comment]
Se inicia el desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado pero se debe esperar a las pruebas integradoras para finalizar esta incidencia.

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.
