### ISSUE TITLE
PYTHON- Modificacion de metodo obtenerConexion

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/chacoDevsTeam-3Semestre#358]
se requiere desarrollar el metodo obtenerConexion se debe obtener la conexion desde el pool (video 4)

**Comment by JuanValladaresv2** [comment]
Se comienza desarrollo

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.
