### ISSUE TITLE
PYTHON- Pruebas creando objetos del Pool de conexiones

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/chacoDevsTeam-3Semestre#359]
Se requiere realizar pruebas sobre el metodo obtenerConexion(), ademas de corregir el error en el metodo obtenerPool

**Comment by naty33** [comment]
Se inicia el desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado, pero se debe esperar a las pruebas integradoras para cerrar esta incidencia

**Comment by patiky** [comment]
![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/88114775/5be55bcf-3be0-4f1d-9b05-53d8a4a13307)

Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.
