### ISSUE TITLE
JAVASCRIPT- Clase Producto

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/chacoDevsTeam-3Semestre#360]
se requiere crear la clase producto la cual cuente con un atributo estatico contadorProducto, y los siguientes atributos  idProducto, nombre, precio. se requiere encapsular sus atributos y crear el metodo toString()

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado, pero se debe esperar a las pruebas integradoras para cerrar esta incidencia

**Comment by Renzo-Espinola** [comment]
Integrado, pero se debe esperar a las pruebas integradoras para cerrar esta incidencia

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.

**Comment by patiky** [comment]
![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/88114775/1ee7faa1-ad6f-466f-bf4f-3371ad2b250e)
