### ISSUE TITLE
JAVASCRIPT - Clase Orden

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/chacoDevsTeam-3Semestre#361]
se requiere crear la clase Orden la cual cuente con dos atributos estaticos contadorOrdenes y MAX_PRODUCTOS un atributo idOrden y 3  metodos.   agregar Producto el cual debera recibir un parametro del tipo Producto y debera ir creando una coleccion de Productos hasta el maximo  definido en el atributo estatico MAX_PRODUCTOS.  calcularTotal debera realizar la suma de los precios de los productos mostrarOrden debera mostrar el idOrden una lista de los productos que integran la orden y la sumatoria total de los precios

**Comment by Renzo-Espinola** [comment]
Realizando la review el codigo, se le informa al desarrollador que falta el metodo mostrarOrden()

**Comment by Federico65744** [comment]
Se comienza el desarrolllo.

**Comment by Renzo-Espinola** [comment]
Integrado, pero se debe esperar a las pruebas integradoras para cerrar esta incidencia

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.

**Comment by patiky** [comment]
![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/88114775/9e7c4d5d-6125-4cd3-9996-e3cc013e40fc)
