### ISSUE TITLE
JAVASCRIPT - Test

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/chacoDevsTeam-3Semestre#362]
Se debera crear varios productos y agregar a una orden mediante el metodo agregarProducto, luego utilizar el metodo mostrarOrden().
     crear 3 productos agregar a una orden1
     crear 4 productos agregar a una orden2
     crear 6 productos y agregar a una orden3

**Comment by NicoBalbuena** [comment]
Se inicia el desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado, pero se debe esperar a las pruebas integradoras para cerrar esta incidencia

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.

**Comment by patiky** [comment]
![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/88114775/91255fe2-ceef-4405-b9dc-bc358dabbd23)
