### ISSUE TITLE
PYTHON 2 ETAPA - Correccion de mensaje Autor en Service LIBRO

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#363]
Se debe mejorar el mensaje que se muestra por pantalla:
AUTOR
Debe ingresar un modo de registro
1: Nombre: 
2: Apellido: 
3: id:3
Autor id: 1

clase: service_libro  linea : 29

**Comment by JuanValladaresv2** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
integrado

**Comment by Renzo-Espinola** [comment]
Prueba final realizada con exito.
