### ISSUE TITLE
PYTHON 2 ETAPA - Correccion de mensaje LIBRO en Service Solicitud

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/chacoDevsTeam-3Semestre#364]
Se requiere mejorar el siguiente mensaje que se muestra en el service solicitud
LIBRO
Debe ingresar un modo de registro
1: Titulo: 
2: ISBN: 
3: id:

metodo: service_solicitud_alta

Clase service_solicitud linea:  19

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado

**Comment by Renzo-Espinola** [comment]
Prueba final realizada con exito.
