### ISSUE TITLE
JAVA-Creación de la clase Persona

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/chacoDevsTeam-3Semestre#369]
Se requiere crear el proyecto ListarPersonas, crear una clase Persona con los siguientes atributos id(String), nombre(String), telefono(String), email(String) y un atributo estatico numeroPersonas(int).
 Se requiere encapsular sus atributos, crear el metodo toString() 
 Crear un metodo estatico main para probar el objeto Persona (VIdeo 3, 4 y 5).

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado, pero se debe esperar a las pruebas integradoras para cerrar esta incidencia

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.

**Comment by patiky** [comment]
![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/88114775/f1a76f24-4b97-4563-8937-54822f721894)
