### ISSUE TITLE
JAVA- Creamos el Menu

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/chacoDevsTeam-3Semestre#370]
se requiere modificar el nombre de la clase main a ListadoPersonasApp se debe crear la estructura de menu en un metodo, con las siguientes opciones
1.Agregar 2.Listar 3.Salir     (este menu debe estar contenido dentro de un ciclo while (Video 6 y 7))

**Comment by AlejoHGZ** [comment]
Se inicia el desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado, pero se debe esperar a las pruebas integradoras para cerrar esta incidencia

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.

**Comment by patiky** [comment]
![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/88114775/2ad2c0c6-be53-4db2-ab95-03b114e1be6d)
