### ISSUE TITLE
JAVA - Agregamos el try catch y el método ejecutarOperación() Incorporamos lambda

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/chacoDevsTeam-3Semestre#371]
se requiere crear el metodo ejecutarOperacion() crear un switch con las opciones 1 y 2
se requiere agregar try catch al metodo ejecutarOperacion() (Video 8 , 9 y 10)

**Comment by DiosJuanVero2015** [comment]
Se inicia Desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado, pero se debe esperar a las pruebas integradoras para cerrar esta incidencia

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.

**Comment by patiky** [comment]
![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/88114775/bf629fc5-a1cd-4b18-b984-d1145b8bed6e)
