### ISSUE TITLE
JAVA - Fin metodo ejecutarOperacion() y pruebas- Diagrama Persona.uxf

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/chacoDevsTeam-3Semestre#372]
Se requiere agregar la opcion 3 del switch en el metodo ejecutarOperacion() 
Realizar pruebas video 11
Realizar el diagrama de persona.uxf en VC y subirlo en la carpeta Leccion10

**Comment by Renzo-Espinola** [comment]
Se comienza el desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado el codigo.

**Comment by Renzo-Espinola** [comment]
Se adjunta el log de pruebas:
******* Listado de Personas *******
1. Agregar
2. Listar
3. Salir
Digite una de las opciones: 1
Digite el nombre: Renzo Espinola
Digite el telefono: 3624909883
Digite el Correorespinola@gmail.com
La Lista tiene : 1 elementos

******* Listado de Personas *******
1. Agregar
2. Listar
3. Salir
Digite una de las opciones: 2
Listado de personas: 
Persona{id=1, nombre='Renzo Espinola', tel='3624909883', email='respinola@gmail.com'}

******* Listado de Personas *******
1. Agregar
2. Listar
3. Salir
Digite una de las opciones: q
Ocurrio un Error: For input string: "q"

******* Listado de Personas *******
1. Agregar
2. Listar
3. Salir
Digite una de las opciones: 4
Opcion incorrecta: 4

******* Listado de Personas *******
1. Agregar
2. Listar
3. Salir
Digite una de las opciones: 0
Opcion incorrecta: 0

******* Listado de Personas *******
1. Agregar
2. Listar
3. Salir
Digite una de las opciones: -1
Opcion incorrecta: -1

******* Listado de Personas *******
1. Agregar
2. Listar
3. Salir
Digite una de las opciones: 3
Hasta Pronto.


Process finished with exit code 0

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias, se procede a cerrar esta incidencia.

**Comment by patiky** [comment]
![Image](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/assets/88114775/9d4f5628-ed68-4122-b253-0c1627c20ded)
