### ISSUE TITLE
Python-clase CursorDelPool

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#416]
Crear la clase CursorDelPool(Video 3 y 4)

**Comment by Renzo-Espinola** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado

**Comment by NicoBalbuena** [comment]
Se realizaron la pruebas correspondientes.Se cierra ticket-Felices vacaciones =)
