### ISSUE TITLE
Python-CursorDelPool

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#417]
Realizar las pruebas del CursorDelPool(video 5 y 6)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado.

**Comment by NicoBalbuena** [comment]
Se realizaron la pruebas correspondientes.Se cierra ticket
