### ISSUE TITLE
Python-PersonaDao

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#418]
Realizar pruebas de PersonaDao(Video 7 y 8)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado.

**Comment by NicoBalbuena** [comment]
Se realizaron la pruebas correspondientes.Se cierra ticket-Felices Vacaciones =)
