### ISSUE TITLE
Java-clase estudiante

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#419]
Crear la clase estudiante(Video 1).Crear la clase estudiante y cada uno de sus atributos.Y agregar diferentes constructores

**Comment by JuanValladaresv2** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado se esperan por las pruebas

**Comment by NicoBalbuena** [comment]
Se realizaron la pruebas correspondientes.Se cierra ticket-Felices vacaciones =)
