### ISSUE TITLE
Java-Agregar try y catch

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#421]
Agregar try y catch(Video 4).Set de cada una de las variables y finalizar metodo listar(Video 5)

**Comment by AlejoHGZ** [comment]
se inicia desarrollo

**Comment by Renzo-Espinola** [comment]
integrado se esperan por las pruebas

**Comment by NicoBalbuena** [comment]
Se realizaron la pruebas correspondientes.Se cierra ticket-Felices vacaciones =)
