### ISSUE TITLE
Java-pruebas del metodo buscarEstudiantePorld

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#423]
Hacer pruebas del metodo buscarEstudiantePorld(Video 8).Sumar el metodo agregarEstudiante(Video 9 y 10)

**Comment by DiosJuanVero2015** [comment]
Se inicia Desarrollo

**Comment by Renzo-Espinola** [comment]
integrado se esperan por las pruebas

**Comment by NicoBalbuena** [comment]
Se realizaron la pruebas correspondientes.Se cierra ticket-Felices vacaciones =)
