### ISSUE TITLE
Java-Pruebas Del metodo agregarEstudiantes

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#424]
Realizar Pruebas Del metodo agregarEstudiantes(Video 11 y 12)

**Comment by Federico65744** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado se esperan por las pruebas

**Comment by NicoBalbuena** [comment]
Se realizaron la pruebas correspondientes.Se cierra ticket-Felices vacaciones =)
