### ISSUE TITLE
Java-método modificarEstudiante

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/chacoDevsTeam-3Semestre#425]
Agregar método modificarEstudiante y luego probarlo.(Video 13 y 14)

**Comment by naty33** [comment]
Se integra al desarrollo

**Comment by Renzo-Espinola** [comment]
se revirtio ya que poseia errores

**Comment by NicoBalbuena** [comment]
Se realizaron la pruebas correspondientes.Se cierra ticket-Felices vacaciones =)
