### ISSUE TITLE
JAVASCRIPT-Funciones de tipo self y invoking

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#70]
Se requiere desarrollar una función de tipo self y mostrar por consola (video 4).

**Comment by JuanValladaresv2** [comment]
Se comienza el desarrollo

**Comment by Renzo-Espinola** [comment]
finalizado el desarrollo, se integra, pero mueve a testing hasta que se hagan pruebas integradoras.

**Comment by TatianaGimenezRios** [comment]
Testing ok.

**Comment by TatianaGimenezRios** [comment]
closes [JAVASCRIPT-Funciones de tipo self y invoking#70](https://github.com/CodeSystem2022/chacoDevsTeam-3Semestre/issues/70)
