### ISSUE TITLE
JAVASCRIPT-Funciones del tipo expresión

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#71]
Se solicita que se cree una función de tipo anónima y mostrar por consola (video 3).

**Comment by JuanValladaresv2** [comment]
Se comienza el desarrollo

**Comment by Renzo-Espinola** [comment]
finalizado el desarrollo, se integra, pero mueve a testing hasta que se hagan pruebas integradoras.

**Comment by TatianaGimenezRios** [comment]
Testing ok

**Comment by TatianaGimenezRios** [comment]
closes chacoDevsTeam-3Semestre #71
