### ISSUE TITLE
JAVASCRIPT-Tipos de datos en una función

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#72]
Se requiere crear una función y mostrar por consola si estas corresponden o no a un objeto tipo función (typeof), video 5.

**Comment by Renzo-Espinola** [comment]
finalizado el desarrollo, se integra, pero mueve a testing hasta que se hagan pruebas integradoras

**Comment by TatianaGimenezRios** [comment]
Testing ok.

**Comment by TatianaGimenezRios** [comment]
closes chacoDevsTeam-3Semestre #90
