### ISSUE TITLE
JAVASCRIPT-Funciones flecha

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#73]
Se requiere desarrollar una función con estructura de flecha, mostrar por consola el resultado (video 6).

**Comment by Renzo-Espinola** [comment]
finalizado el desarrollo, se integra, pero mueve a testing hasta que se hagan pruebas integradoras

**Comment by TatianaGimenezRios** [comment]
Testing ok.

**Comment by TatianaGimenezRios** [comment]
closes chacoDevsTeam-3Semestre #91
