### ISSUE TITLE
JAVASCRIPT-Argumentos y parámetros

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#74]
Se requiere crear una función con n números de parámetros y a ésta función pasarle un número n de argumentos (video 7).

**Comment by Renzo-Espinola** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
Finalizado el desarrollo

**Comment by TatianaGimenezRios** [comment]
Testing ok.

**Comment by TatianaGimenezRios** [comment]
closes chacoDevsTeam-3Semestre #83
