### ISSUE TITLE
JAVASCRIPT-Concepto hoisting

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#75]
Se solicita crear una función, la cual reciba n números de argumentos y aplicar el concepto de hoisting (video 8).

**Comment by Renzo-Espinola** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
finalizado el desarrollo

**Comment by TatianaGimenezRios** [comment]
Testing  ok.

**Comment by TatianaGimenezRios** [comment]
closes chacoDevsTeam-3Semestre #84
