### ISSUE TITLE
JAVASCRIPT-Paso por valor

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#76]
Se solicita desarrollar una función que aplique concepto de paso por valor (video 9).

**Comment by Renzo-Espinola** [comment]
finalizado el desarrollo, se integra, pero mueve a testing hasta que se hagan pruebas integradoras.

**Comment by TatianaGimenezRios** [comment]
Testing ok.

**Comment by TatianaGimenezRios** [comment]
closes chacoDevsTeam-3Semestre #76
