### ISSUE TITLE
JAVASCRIPT-Paso por referencia

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#77]
Se solicita desarrollar una función que aplique el concepto de paso por referencia (video 10).

**Comment by DiosJuanVero2015** [comment]
Se comienza con el Desarrollo

**Comment by Renzo-Espinola** [comment]
finalizado el desarrollo, se integra, pero mueve a testing hasta que se hagan pruebas integradoras.

**Comment by TatianaGimenezRios** [comment]
Testing ok.

**Comment by TatianaGimenezRios** [comment]
closes chacoDevsTeam-3Semestre #88
