### ISSUE TITLE
PYTHON-Creación de la clase: catalogo_peliculas

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#79]
Se requiere desarrollar la clase CatalogoPeliculas la cual debe tener 3 métodos de clase: agregar_peliculas, listar_peliculas y eliminar_peliculas (video 3).
La responsabilidad de esta clase es de realizar las operaciones sobre el archivo de película.txt

**Comment by Federico65744** [comment]
Se comienza con el desarrollo.

**Comment by Renzo-Espinola** [comment]
Se integro, pero se debe esperar a la integracion del resto de los tickets para avanzar a testing

**Comment by TatianaGimenezRios** [comment]
Testing ok.

**Comment by TatianaGimenezRios** [comment]
closes chacoDevsTeam-3Semestre #107
