### ISSUE TITLE
PYTHON-Creación de: test_catalogo_peliculas

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#80]
Se requiere crear la clase test_catalogo_peliculas la cual debe contener un bucle, en el cual se solicita las opciones al usuario (video 4).

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
Se integro.

**Comment by TatianaGimenezRios** [comment]
Testing ok.

**Comment by TatianaGimenezRios** [comment]
closes chacoDevsTeam-3Semestre #85
