### ISSUE TITLE
PYTHON-Comenzamos con las pruebas ingresando las otras clases, parte 1 y Parte 2

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#81]
Iniciar el desarrollo de esta ticket una vez que este integrado el ticket #80 
Requerimiento: desarrollar una estructura de control de las opciones ingresadas por el usuario; realizar pruebas de integración (videos 5 y 6).

**Comment by AlejoHGZ** [comment]
Se Comienza el desarollo

**Comment by Renzo-Espinola** [comment]
Se integro, pero se debe esperar a la integracion del resto de los tickets para avanzar a testing

**Comment by TatianaGimenezRios** [comment]
Testing ok.

**Comment by TatianaGimenezRios** [comment]
closes #81
