### ISSUE TITLE
JAVA-ARGUMENTOS VARIABLES

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#92]
Se requiere desarrollar una clase TestArgumentosVariables el cual contenga 2 métodos estáticos, en donde 1 método reciba argumentos variables y el otro método reciba parámetros y argumento variable (videos 1 y 2).

**Comment by Renzo-Espinola** [comment]
Se comienza desarrollo.

**Comment by TatianaGimenezRios** [comment]
Testing ok.

**Comment by TatianaGimenezRios** [comment]
closes chacoDevsTeam-3Semestre #92
