### ISSUE TITLE
JAVA-ENUMERACIONES-DÍAS

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/chacoDevsTeam-3Semestre#94]
Se requiere crear un método estático indicarDiaSemana el cual utilizar una sentencia switch (video 4).

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by TatianaGimenezRios** [comment]
Testing ok.

**Comment by TatianaGimenezRios** [comment]
closes chacoDevsTeam-3Semestre #94
